const SUCCESS = "SUCCESS";
const FAILURE = "FAILURE";
const WARNING = "WARNING";
const AUTH_RESET_ALL = "AUTH_RESET_ALL";
const AUTH_SIGNUP_REQUEST = "AUTH_SIGNUP_REQUEST";
const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";
const AUTH_SIGNIN_REQUEST = "AUTH_SIGNIN_REQUEST";
const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
const AUTH_SIGNIN_FAILURE = "AUTH_SIGNIN_FAILURE";
const AUTH_FORGOT_PASSWORD_REQUEST = "AUTH_FORGOT_PASSWORD_REQUEST";
const AUTH_FORGOT_PASSWORD_SUCCESS = "AUTH_FORGOT_PASSWORD_SUCCESS";
const AUTH_FORGOT_PASSWORD_FAILURE = "AUTH_FORGOT_PASSWORD_FAILURE";
const AUTH_CHECK_RESET_PASSWORD_REQUEST = "AUTH_CHECK_RESET_PASSWORD_REQUEST";
const AUTH_CHECK_RESET_PASSWORD_SUCCESS = "AUTH_CHECK_RESET_PASSWORD_SUCCESS";
const AUTH_CHECK_RESET_PASSWORD_FAILURE = "AUTH_CHECK_RESET_PASSWORD_FAILURE";
const AUTH_RESET_PASSWORD_REQUEST = "AUTH_RESET_PASSWORD_REQUEST";
const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
const AUTH_RESET_PASSWORD_FAILURE = "AUTH_RESET_PASSWORD_FAILURE";
const AUTH_READ_PROFILE_REQUEST = "AUTH_READ_PROFILE_REQUEST";
const AUTH_READ_PROFILE_SUCCESS = "AUTH_READ_PROFILE_SUCCESS";
const AUTH_READ_PROFILE_FAILURE = "AUTH_READ_PROFILE_FAILURE";
const AUTH_UPDATE_PROFILE_REQUEST = "AUTH_UPDATE_PROFILE_REQUEST";
const AUTH_UPDATE_PROFILE_SUCCESS = "AUTH_UPDATE_PROFILE_SUCCESS";
const AUTH_UPDATE_PROFILE_FAILURE = "AUTH_UPDATE_PROFILE_FAILURE";
const AUTH_CHANGE_PASSWORD_REQUEST = "AUTH_CHANGE_PASSWORD_REQUEST";
const AUTH_CHANGE_PASSWORD_SUCCESS = "AUTH_CHANGE_PASSWORD_SUCCESS";
const AUTH_CHANGE_PASSWORD_FAILURE = "AUTH_CHANGE_PASSWORD_FAILURE";
const AUTH_CHECK_SESSION_REQUEST = "AUTH_CHECK_SESSION_REQUEST";
const AUTH_CHECK_SESSION_SUCCESS = "AUTH_CHECK_SESSION_SUCCESS";
const AUTH_CHECK_SESSION_FAILURE = "AUTH_CHECK_SESSION_FAILURE";
const AUTH_SIGNOUT_REQUEST = "AUTH_SIGNOUT_REQUEST";
const USER_TEST_REQUEST = "USER_TEST_REQUEST";
const USER_TEST_SUCCESS = "USER_TEST_SUCCESS";
const USER_TEST_FAILURE = "USER_TEST_FAILURE";

export {
  SUCCESS,
  FAILURE,
  WARNING,
  AUTH_RESET_ALL,
  AUTH_SIGNUP_REQUEST,
  AUTH_SIGNUP_SUCCESS,
  AUTH_SIGNUP_FAILURE,
  AUTH_SIGNIN_REQUEST,
  AUTH_SIGNIN_SUCCESS,
  AUTH_SIGNIN_FAILURE,
  AUTH_FORGOT_PASSWORD_REQUEST,
  AUTH_FORGOT_PASSWORD_SUCCESS,
  AUTH_FORGOT_PASSWORD_FAILURE,
  AUTH_CHECK_RESET_PASSWORD_REQUEST,
  AUTH_CHECK_RESET_PASSWORD_SUCCESS,
  AUTH_CHECK_RESET_PASSWORD_FAILURE,
  AUTH_RESET_PASSWORD_REQUEST,
  AUTH_RESET_PASSWORD_SUCCESS,
  AUTH_RESET_PASSWORD_FAILURE,
  AUTH_READ_PROFILE_REQUEST,
  AUTH_READ_PROFILE_SUCCESS,
  AUTH_READ_PROFILE_FAILURE,
  AUTH_UPDATE_PROFILE_REQUEST,
  AUTH_UPDATE_PROFILE_SUCCESS,
  AUTH_UPDATE_PROFILE_FAILURE,
  AUTH_CHANGE_PASSWORD_REQUEST,
  AUTH_CHANGE_PASSWORD_SUCCESS,
  AUTH_CHANGE_PASSWORD_FAILURE,
  AUTH_CHECK_SESSION_REQUEST,
  AUTH_CHECK_SESSION_SUCCESS,
  AUTH_CHECK_SESSION_FAILURE,
  AUTH_SIGNOUT_REQUEST,
  USER_TEST_REQUEST,
  USER_TEST_SUCCESS,
  USER_TEST_FAILURE,
};
